### ISSUE TITLE
gem install fails on mac

### ISSUE THREAD

**Issue by nguinasso** [kirbs-/sensi#1]
On my Mac notenook i tried to install sensi which failed. 
Any suggestions?

~$ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
~$gem -v
2.0.14
~$gem env
RubyGems Environment:
- RUBYGEMS VERSION: 2.0.14
- RUBY VERSION: 2.0.0 (2014-05-08 patchlevel 481) [universal.x86_64-darwin14]
- INSTALLATION DIRECTORY: /Library/Ruby/Gems/2.0.0
- RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
- EXECUTABLE DIRECTORY: /usr/bin
- RUBYGEMS PLATFORMS:
  - ruby
  - universal-darwin-14
- GEM PATHS:
  - /Library/Ruby/Gems/2.0.0
  - /Users/norman/.gem/ruby/2.0.0
  - /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :backtrace => false
  - :bulk_threshold => 1000
- REMOTE SOURCES:
  - https://rubygems.org/
    ~$gem install sensi
    Fetching: json-1.8.3.gem (100%)
    ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
    ~$sudo gem install sensi
    Password:
    Fetching: json-1.8.3.gem (100%)
    Building native extensions.  This could take a while...
    Successfully installed json-1.8.3
    Fetching: multi_xml-0.5.5.gem (100%)
    Successfully installed multi_xml-0.5.5
    Fetching: httparty-0.13.7.gem (100%)
    When you HTTParty, you must party hard!
    Successfully installed httparty-0.13.7
    Fetching: curb-0.9.3.gem (100%)
    Building native extensions.  This could take a while...
    ERROR:  Error installing sensi:
    ERROR: Failed to build gem native extension.
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
    checking for curl-config... yes
    checking for curlinfo_appconnect_time... no
    checking for curlinfo_redirect_time... no
    checking for curlinfo_response_code... no
    checking for curlinfo_filetime... no
    checking for curlinfo_redirect_count... no
    checking for curlinfo_os_errno... no
    checking for curlinfo_num_connects... no
    checking for curlinfo_ftp_entry_path... no
    checking for curl_version_ssl... no
    checking for curl_version_libz... no
    checking for curl_version_ntlm... no
    checking for curl_version_gssnegotiate... no
    checking for curl_version_debug... no
    checking for curl_version_asynchdns... no
    checking for curl_version_spnego... no
    checking for curl_version_largefile... no
    checking for curl_version_idn... no
    checking for curl_version_sspi... no
    checking for curl_version_conv... no
    checking for curl_version_http2... no
    checking for curlproxy_http... no
    checking for curlproxy_socks4... no
    checking for curlproxy_socks4a... no
    checking for curlproxy_socks5... no
    checking for curlauth_basic... no
    checking for curlauth_digest... no
    checking for curlauth_gssnegotiate... no
    checking for curlauth_ntlm... no
    checking for curlauth_anysafe... no
    checking for curlauth_any... no
    checking for curle_tftp_notfound... no
    checking for curle_tftp_perm... no
    checking for curle_tftp_diskfull... no
    checking for curle_tftp_illegal... no
    checking for curle_tftp_unknownid... no
    checking for curle_tftp_exists... no
    checking for curle_tftp_nosuchuser... no
    checking for curle_send_fail_rewind... no
    checking for curle_ssl_engine_initfailed... no
    checking for curle_login_denied... no
    checking for curlmopt_maxconnects... no
    checking for curlopt_seekfunction... no
    checking for curlopt_seekdata... no
    checking for curlopt_sockoptfunction... no
    checking for curlopt_sockoptdata... no
    checking for curlopt_opensocketfunction... no
    checking for curlopt_opensocketdata... no
    checking for curle_conv_failed... no
    checking for curle_conv_reqd... no
    checking for curle_ssl_cacert_badfile... no
    checking for curle_remote_file_not_found... no
    checking for curle_ssh... no
    checking for curle_ssl_shutdown_failed... no
    checking for curle_again... no
    checking for curle_ssl_crl_badfile... no
    checking for curle_ssl_issuer_error... no
    checking for curlinfo_redirect_url... no
    checking for curlopt_username... no
    checking for curlopt_password... no
    checking for curlinfo_primary_ip... no
    checking for curlauth_digest_ie... no
    checking for curlftpmethod_multicwd... no
    checking for curlftpmethod_nocwd... no
    checking for curlftpmethod_singlecwd... no
    checking for curlm_bad_socket... no
    checking for curlm_unknown_option... no
    checking for curl_multi_timeout()... no
    checking for curl_multi_fdset()... no
    checking for curl_multi_perform()... no
    checking for curlopt_interleavefunction... no
    checking for curlopt_interleavedata... no
    checking for curlopt_chunk_bgn_function... no
    checking for curlopt_chunk_end_function... no
    checking for curlopt_chunk_data... no
    checking for curlopt_fnmatch_function... no
    checking for curlopt_fnmatch_data... no
    checking for curlopt_errorbuffer... no
    checking for curlopt_stderr... no
    checking for curlopt_failonerror... no
    checking for curlopt_url... no
    checking for curlopt_protocols... no
    checking for curlopt_redir_protocols... no
    checking for curlopt_proxy... no
    checking for curlopt_proxyport... no
    checking for curlopt_proxytype... no
    checking for curlopt_noproxy... no
    checking for curlopt_httpproxytunnel... no
    checking for curlopt_socks5_gssapi_service... no
    checking for curlopt_socks5_gssapi_nec... no
    checking for curlopt_interface... no
    checking for curlopt_localport... no
    checking for curlopt_dns_cache_timeout... no
    checking for curlopt_dns_use_global_cache... no
    checking for curlopt_buffersize... no
    checking for curlopt_port... no
    checking for curlopt_tcp_nodelay... no
    checking for curlopt_address_scope... no
    checking for curlopt_netrc... no
    checking for curl_netrc_optional... no
    checking for curl_netrc_ignored... no
    checking for curl_netrc_required... no
    checking for curlopt_netrc_file... no
    checking for curlopt_userpwd... no
    checking for curlopt_proxyuserpwd... no
    checking for curlopt_username... no
    checking for curlopt_password... no
    checking for curlopt_password... no
    checking for curlopt_password... no
    checking for curlopt_httpauth... no
    checking for curlauth_digest_ie... no
    checking for curlauth_only... no
    checking for curlopt_tlsauth_type... no
    checking for curlopt_tlsauth_srp... no
    checking for curlopt_tlsauth_username... no
    checking for curlopt_tlsauth_password... no
    checking for curlopt_proxyauth... no
    checking for curlopt_autoreferer... no
    checking for curlopt_encoding... no
    checking for curlopt_followlocation... no
    checking for curlopt_unrestricted_auth... no
    checking for curlopt_maxredirs... no
    checking for curlopt_postredir... no
    checking for curlopt_put... no
    checking for curlopt_post... no
    checking for curlopt_postfields... no
    checking for curlopt_postfieldsize... no
    checking for curlopt_postfieldsize_large... no
    checking for curlopt_copypostfields... no
    checking for curlopt_httppost... no
    checking for curlopt_referer... no
    checking for curlopt_useragent... no
    checking for curlopt_httpheader... no
    checking for curlopt_http200aliases... no
    checking for curlopt_cookie... no
    checking for curlopt_cookiefile... no
    checking for curlopt_cookiejar... no
    checking for curlopt_cookiesession... no
    checking for curlopt_cookielist... no
    checking for curlopt_httpget... no
    checking for curlopt_http_version... no
    checking for curl_http_version_none... no
    checking for curl_http_version_1_0... no
    checking for curl_http_version_1_1... no
    checking for curlopt_ignore_content_length... no
    checking for curlopt_http_content_decoding... no
    checking for curlopt_http_transfer_decoding... no
    checking for curlopt_mail_from... no
    checking for curlopt_mail_rcpt... no
    checking for curlopt_tftp_blksize... no
    checking for curlopt_ftpport... no
    checking for curlopt_quote... no
    checking for curlopt_postquote... no
    checking for curlopt_prequote... no
    checking for curlopt_dirlistonly... no
    checking for curlopt_append... no
    checking for curlopt_ftp_use_eprt... no
    checking for curlopt_ftp_use_epsv... no
    checking for curlopt_ftp_use_pret... no
    checking for curlopt_ftp_create_missing_dirs... no
    checking for curlopt_ftp_response_timeout... no
    checking for curlopt_ftp_alternative_to_user... no
    checking for curlopt_ftp_skip_pasv_ip... no
    checking for curlopt_ftpsslauth... no
    checking for curlftpauth_default... no
    checking for curlftpauth_ssl... no
    checking for curlftpauth_tls... no
    checking for curlopt_ftp_ssl_ccc... no
    checking for curlftpssl_ccc_none... no
    checking for curlftpssl_ccc_passive... no
    checking for curlftpssl_ccc_active... no
    checking for curlopt_ftp_account... no
    checking for curlopt_ftp_filemethod... no
    checking for curlftpmethod_multicwd... no
    checking for curlftpmethod_nocwd... no
    checking for curlftpmethod_singlecwd... no
    checking for curlopt_rtsp_request... no
    checking for curl_rtspreq_options... no
    checking for curl_rtspreq_describe... no
    checking for curl_rtspreq_announce... no
    checking for curl_rtspreq_setup... no
    checking for curl_rtspreq_play... no
    checking for curl_rtspreq_pause... no
    checking for curl_rtspreq_teardown... no
    checking for curl_rtspreq_get_parameter... no
    checking for curl_rtspreq_set_parameter... no
    checking for curl_rtspreq_record... no
    checking for curl_rtspreq_receive... no
    checking for curlopt_rtsp_session_id... no
    checking for curlopt_rtsp_stream_uri... no
    checking for curlopt_rtsp_transport... no
    checking for curlopt_rtsp_header... no
    checking for curlopt_rtsp_client_cseq... no
    checking for curlopt_rtsp_server_cseq... no
    checking for curlopt_transfertext... no
    checking for curlopt_proxy_transfer_mode... no
    checking for curlopt_crlf... no
    checking for curlopt_range... no
    checking for curlopt_resume_from... no
    checking for curlopt_resume_from_large... no
    checking for curlopt_customrequest... no
    checking for curlopt_filetime... no
    checking for curlopt_nobody... no
    checking for curlopt_infilesize... no
    checking for curlopt_infilesize_large... no
    checking for curlopt_upload... no
    checking for curlopt_maxfilesize... no
    checking for curlopt_maxfilesize_large... no
    checking for curlopt_timecondition... no
    checking for curlopt_timevalue... no
    checking for curlopt_timeout... no
    checking for curlopt_timeout_ms... no
    checking for curlopt_low_speed_limit... no
    checking for curlopt_low_speed_time... no
    checking for curlopt_max_send_speed_large... no
    checking for curlopt_max_recv_speed_large... no
    checking for curlopt_maxconnects... no
    checking for curlopt_closepolicy... no
    checking for curlopt_fresh_connect... no
    checking for curlopt_forbid_reuse... no
    checking for curlopt_connecttimeout... no
    checking for curlopt_connecttimeout_ms... no
    checking for curlopt_ipresolve... no
    checking for curl_ipresolve_whatever... no
    checking for curl_ipresolve_v4... no
    checking for curl_ipresolve_v6... no
    checking for curlopt_connect_only... no
    checking for curlopt_use_ssl... no
    checking for curlusessl_none... no
    checking for curlusessl_try... no
    checking for curlusessl_control... no
    checking for curlusessl_all... no
    checking for curlopt_resolve... no
    checking for curlopt_sslcert... no
    checking for curlopt_sslcerttype... no
    checking for curlopt_sslkey... no
    checking for curlopt_sslkeytype... no
    checking for curlopt_keypasswd... no
    checking for curlopt_sslengine... no
    checking for curlopt_sslengine_default... no
    checking for curlopt_sslversion... no
    checking for curl_sslversion_default... no
    checking for curl_sslversion_tlsv1... no
    checking for curl_sslversion_sslv2... no
    checking for curl_sslversion_sslv3... no
    checking for curl_sslversion_tlsv1_0... no
    checking for curl_sslversion_tlsv1_1... no
    checking for curl_sslversion_tlsv1_2... no
    checking for curlopt_ssl_verifypeer... no
    checking for curlopt_cainfo... no
    checking for curlopt_issuercert... no
    checking for curlopt_capath... no
    checking for curlopt_crlfile... no
    checking for curlopt_ssl_verifyhost... no
    checking for curlopt_certinfo... no
    checking for curlopt_random_file... no
    checking for curlopt_egdsocket... no
    checking for curlopt_ssl_cipher_list... no
    checking for curlopt_ssl_sessionid_cache... no
    checking for curlopt_krblevel... no
    checking for curlopt_ssh_auth_types... no
    checking for curlopt_ssh_host_public_key_md5... no
    checking for curlopt_ssh_public_keyfile... no
    checking for curlopt_ssh_private_keyfile... no
    checking for curlopt_ssh_knownhosts... no
    checking for curlopt_ssh_keyfunction... no
    checking for curlkhstat_fine_add_to_file... no
    checking for curlkhstat_fine... no
    checking for curlkhstat_reject... no
    checking for curlkhstat_defer... no
    checking for curlopt_ssh_keydata... no
    checking for curlopt_private... no
    checking for curlopt_share... no
    checking for curlopt_new_file_perms... no
    checking for curlopt_new_directory_perms... no
    checking for curlopt_telnetoptions... no
    checking for curle_not_built_in... no
    checking for curle_obsolete... no
    checking for curlopt_gssapi_delegation... no
    checking for curlgssapi_delegation_policy_flag... no
    checking for curlgssapi_delegation_flag... no
    checking for CURLM_ADDED_ALREADY... no
    checking for curlopt_unix_socket_path... no
    checking for curl_easy_escape... no
    checking for rb_thread_blocking_region()... yes
    checking for ruby/thread.h... yes
    checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
    creating curb_config.h
    creating Makefile

make "DESTDIR="
compiling curb.c
In file included from curb.c:8:
In file included from ./curb.h:12:
In file included from /opt/local/include/curl/curl.h:35:
/opt/local/include/curl/curlrules.h:143:6: error: '**curl_rule_01**' declared as an array with a negative size
    [CurlchkszEQ(long, CURL_SIZEOF_LONG)];
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/curl/curlrules.h:132:27: note: expanded from macro 'CurlchkszEQ'
# define CurlchkszEQ(t, s) sizeof(t) == s ? 1 : -1

```
                      ^~~~~~~~~~~~~~~~~~~~~~~
```

/opt/local/include/curl/curlrules.h:153:6: error: '**curl_rule_02**' declared as an array with a negative size
    [CurlchkszEQ(curl_off_t, CURL_SIZEOF_CURL_OFF_T)];
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/curl/curlrules.h:132:27: note: expanded from macro 'CurlchkszEQ'
# define CurlchkszEQ(t, s) sizeof(t) == s ? 1 : -1

```
                      ^~~~~~~~~~~~~~~~~~~~~~~
```

2 errors generated.
make: **\* [curb.o] Error 1

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/curb-0.9.3 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/curb-0.9.3/ext/gem_make.out

**Comment by kirbs-** [comment]
Looks like you're having issues with curb. Try installing first. If it still fails try downgrading the version. Any version 0.7 or higher will work with sensi.

Also, check all of [curb's dependencies](https://github.com/taf2/curb) are met.

**Comment by nguinasso** [comment]
I installed curl which worked after I did a 
gem update
I still don't seem to install sensi. Am I missing some other gem?

~$gem list

**\* LOCAL GEMS ***

awesome_print (1.7.0)
bigdecimal (1.2.7, 1.2.0)
CFPropertyList (2.3.2, 2.2.8)
curl (0.0.9)
httparty (0.13.7)
io-console (0.4.6, 0.4.2)
json (1.8.3, 1.7.7)
libxml-ruby (2.9.0, 2.6.0)
mini_portile2 (2.1.0)
minitest (5.9.0, 4.3.2)
multi_xml (0.5.5)
nokogiri (1.5.6)
pkg-config (1.1.7)
power_assert (0.3.0)
psych (2.1.0, 2.0.0)
rake (11.2.2, 0.9.6)
rdoc (4.2.2, 4.0.0)
rubycurl (1.7.3)
sqlite3 (1.3.11, 1.3.7)
test-unit (3.2.0, 2.0.0.0)
unidecoder (1.1.2)
~$sudo gem install sensi
Password:
Building native extensions.  This could take a while...
ERROR:  Error installing sensi:
    ERROR: Failed to build gem native extension.

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
```

checking for curl-config... yes
checking for curlinfo_appconnect_time... no
checking for curlinfo_redirect_time... no
checking for curlinfo_response_code... no
checking for curlinfo_filetime... no
checking for curlinfo_redirect_count... no
checking for curlinfo_os_errno... no
checking for curlinfo_num_connects... no
checking for curlinfo_ftp_entry_path... no
checking for curl_version_ssl... no
checking for curl_version_libz... no
checking for curl_version_ntlm... no
checking for curl_version_gssnegotiate... no
checking for curl_version_debug... no
checking for curl_version_asynchdns... no
checking for curl_version_spnego... no
checking for curl_version_largefile... no
checking for curl_version_idn... no
checking for curl_version_sspi... no
checking for curl_version_conv... no
checking for curl_version_http2... no
checking for curlproxy_http... no
checking for curlproxy_socks4... no
checking for curlproxy_socks4a... no
checking for curlproxy_socks5... no
checking for curlauth_basic... no
checking for curlauth_digest... no
checking for curlauth_gssnegotiate... no
checking for curlauth_ntlm... no
checking for curlauth_anysafe... no
checking for curlauth_any... no
checking for curle_tftp_notfound... no
checking for curle_tftp_perm... no
checking for curle_tftp_diskfull... no
checking for curle_tftp_illegal... no
checking for curle_tftp_unknownid... no
checking for curle_tftp_exists... no
checking for curle_tftp_nosuchuser... no
checking for curle_send_fail_rewind... no
checking for curle_ssl_engine_initfailed... no
checking for curle_login_denied... no
checking for curlmopt_maxconnects... no
checking for curlopt_seekfunction... no
checking for curlopt_seekdata... no
checking for curlopt_sockoptfunction... no
checking for curlopt_sockoptdata... no
checking for curlopt_opensocketfunction... no
checking for curlopt_opensocketdata... no
checking for curle_conv_failed... no
checking for curle_conv_reqd... no
checking for curle_ssl_cacert_badfile... no
checking for curle_remote_file_not_found... no
checking for curle_ssh... no
checking for curle_ssl_shutdown_failed... no
checking for curle_again... no
checking for curle_ssl_crl_badfile... no
checking for curle_ssl_issuer_error... no
checking for curlinfo_redirect_url... no
checking for curlopt_username... no
checking for curlopt_password... no
checking for curlinfo_primary_ip... no
checking for curlauth_digest_ie... no
checking for curlftpmethod_multicwd... no
checking for curlftpmethod_nocwd... no
checking for curlftpmethod_singlecwd... no
checking for curlm_bad_socket... no
checking for curlm_unknown_option... no
checking for curl_multi_timeout()... no
checking for curl_multi_fdset()... no
checking for curl_multi_perform()... no
checking for curlopt_interleavefunction... no
checking for curlopt_interleavedata... no
checking for curlopt_chunk_bgn_function... no
checking for curlopt_chunk_end_function... no
checking for curlopt_chunk_data... no
checking for curlopt_fnmatch_function... no
checking for curlopt_fnmatch_data... no
checking for curlopt_errorbuffer... no
checking for curlopt_stderr... no
checking for curlopt_failonerror... no
checking for curlopt_url... no
checking for curlopt_protocols... no
checking for curlopt_redir_protocols... no
checking for curlopt_proxy... no
checking for curlopt_proxyport... no
checking for curlopt_proxytype... no
checking for curlopt_noproxy... no
checking for curlopt_httpproxytunnel... no
checking for curlopt_socks5_gssapi_service... no
checking for curlopt_socks5_gssapi_nec... no
checking for curlopt_interface... no
checking for curlopt_localport... no
checking for curlopt_dns_cache_timeout... no
checking for curlopt_dns_use_global_cache... no
checking for curlopt_buffersize... no
checking for curlopt_port... no
checking for curlopt_tcp_nodelay... no
checking for curlopt_address_scope... no
checking for curlopt_netrc... no
checking for curl_netrc_optional... no
checking for curl_netrc_ignored... no
checking for curl_netrc_required... no
checking for curlopt_netrc_file... no
checking for curlopt_userpwd... no
checking for curlopt_proxyuserpwd... no
checking for curlopt_username... no
checking for curlopt_password... no
checking for curlopt_password... no
checking for curlopt_password... no
checking for curlopt_httpauth... no
checking for curlauth_digest_ie... no
checking for curlauth_only... no
checking for curlopt_tlsauth_type... no
checking for curlopt_tlsauth_srp... no
checking for curlopt_tlsauth_username... no
checking for curlopt_tlsauth_password... no
checking for curlopt_proxyauth... no
checking for curlopt_autoreferer... no
checking for curlopt_encoding... no
checking for curlopt_followlocation... no
checking for curlopt_unrestricted_auth... no
checking for curlopt_maxredirs... no
checking for curlopt_postredir... no
checking for curlopt_put... no
checking for curlopt_post... no
checking for curlopt_postfields... no
checking for curlopt_postfieldsize... no
checking for curlopt_postfieldsize_large... no
checking for curlopt_copypostfields... no
checking for curlopt_httppost... no
checking for curlopt_referer... no
checking for curlopt_useragent... no
checking for curlopt_httpheader... no
checking for curlopt_http200aliases... no
checking for curlopt_cookie... no
checking for curlopt_cookiefile... no
checking for curlopt_cookiejar... no
checking for curlopt_cookiesession... no
checking for curlopt_cookielist... no
checking for curlopt_httpget... no
checking for curlopt_http_version... no
checking for curl_http_version_none... no
checking for curl_http_version_1_0... no
checking for curl_http_version_1_1... no
checking for curlopt_ignore_content_length... no
checking for curlopt_http_content_decoding... no
checking for curlopt_http_transfer_decoding... no
checking for curlopt_mail_from... no
checking for curlopt_mail_rcpt... no
checking for curlopt_tftp_blksize... no
checking for curlopt_ftpport... no
checking for curlopt_quote... no
checking for curlopt_postquote... no
checking for curlopt_prequote... no
checking for curlopt_dirlistonly... no
checking for curlopt_append... no
checking for curlopt_ftp_use_eprt... no
checking for curlopt_ftp_use_epsv... no
checking for curlopt_ftp_use_pret... no
checking for curlopt_ftp_create_missing_dirs... no
checking for curlopt_ftp_response_timeout... no
checking for curlopt_ftp_alternative_to_user... no
checking for curlopt_ftp_skip_pasv_ip... no
checking for curlopt_ftpsslauth... no
checking for curlftpauth_default... no
checking for curlftpauth_ssl... no
checking for curlftpauth_tls... no
checking for curlopt_ftp_ssl_ccc... no
checking for curlftpssl_ccc_none... no
checking for curlftpssl_ccc_passive... no
checking for curlftpssl_ccc_active... no
checking for curlopt_ftp_account... no
checking for curlopt_ftp_filemethod... no
checking for curlftpmethod_multicwd... no
checking for curlftpmethod_nocwd... no
checking for curlftpmethod_singlecwd... no
checking for curlopt_rtsp_request... no
checking for curl_rtspreq_options... no
checking for curl_rtspreq_describe... no
checking for curl_rtspreq_announce... no
checking for curl_rtspreq_setup... no
checking for curl_rtspreq_play... no
checking for curl_rtspreq_pause... no
checking for curl_rtspreq_teardown... no
checking for curl_rtspreq_get_parameter... no
checking for curl_rtspreq_set_parameter... no
checking for curl_rtspreq_record... no
checking for curl_rtspreq_receive... no
checking for curlopt_rtsp_session_id... no
checking for curlopt_rtsp_stream_uri... no
checking for curlopt_rtsp_transport... no
checking for curlopt_rtsp_header... no
checking for curlopt_rtsp_client_cseq... no
checking for curlopt_rtsp_server_cseq... no
checking for curlopt_transfertext... no
checking for curlopt_proxy_transfer_mode... no
checking for curlopt_crlf... no
checking for curlopt_range... no
checking for curlopt_resume_from... no
checking for curlopt_resume_from_large... no
checking for curlopt_customrequest... no
checking for curlopt_filetime... no
checking for curlopt_nobody... no
checking for curlopt_infilesize... no
checking for curlopt_infilesize_large... no
checking for curlopt_upload... no
checking for curlopt_maxfilesize... no
checking for curlopt_maxfilesize_large... no
checking for curlopt_timecondition... no
checking for curlopt_timevalue... no
checking for curlopt_timeout... no
checking for curlopt_timeout_ms... no
checking for curlopt_low_speed_limit... no
checking for curlopt_low_speed_time... no
checking for curlopt_max_send_speed_large... no
checking for curlopt_max_recv_speed_large... no
checking for curlopt_maxconnects... no
checking for curlopt_closepolicy... no
checking for curlopt_fresh_connect... no
checking for curlopt_forbid_reuse... no
checking for curlopt_connecttimeout... no
checking for curlopt_connecttimeout_ms... no
checking for curlopt_ipresolve... no
checking for curl_ipresolve_whatever... no
checking for curl_ipresolve_v4... no
checking for curl_ipresolve_v6... no
checking for curlopt_connect_only... no
checking for curlopt_use_ssl... no
checking for curlusessl_none... no
checking for curlusessl_try... no
checking for curlusessl_control... no
checking for curlusessl_all... no
checking for curlopt_resolve... no
checking for curlopt_sslcert... no
checking for curlopt_sslcerttype... no
checking for curlopt_sslkey... no
checking for curlopt_sslkeytype... no
checking for curlopt_keypasswd... no
checking for curlopt_sslengine... no
checking for curlopt_sslengine_default... no
checking for curlopt_sslversion... no
checking for curl_sslversion_default... no
checking for curl_sslversion_tlsv1... no
checking for curl_sslversion_sslv2... no
checking for curl_sslversion_sslv3... no
checking for curl_sslversion_tlsv1_0... no
checking for curl_sslversion_tlsv1_1... no
checking for curl_sslversion_tlsv1_2... no
checking for curlopt_ssl_verifypeer... no
checking for curlopt_cainfo... no
checking for curlopt_issuercert... no
checking for curlopt_capath... no
checking for curlopt_crlfile... no
checking for curlopt_ssl_verifyhost... no
checking for curlopt_certinfo... no
checking for curlopt_random_file... no
checking for curlopt_egdsocket... no
checking for curlopt_ssl_cipher_list... no
checking for curlopt_ssl_sessionid_cache... no
checking for curlopt_krblevel... no
checking for curlopt_ssh_auth_types... no
checking for curlopt_ssh_host_public_key_md5... no
checking for curlopt_ssh_public_keyfile... no
checking for curlopt_ssh_private_keyfile... no
checking for curlopt_ssh_knownhosts... no
checking for curlopt_ssh_keyfunction... no
checking for curlkhstat_fine_add_to_file... no
checking for curlkhstat_fine... no
checking for curlkhstat_reject... no
checking for curlkhstat_defer... no
checking for curlopt_ssh_keydata... no
checking for curlopt_private... no
checking for curlopt_share... no
checking for curlopt_new_file_perms... no
checking for curlopt_new_directory_perms... no
checking for curlopt_telnetoptions... no
checking for curle_not_built_in... no
checking for curle_obsolete... no
checking for curlopt_gssapi_delegation... no
checking for curlgssapi_delegation_policy_flag... no
checking for curlgssapi_delegation_flag... no
checking for CURLM_ADDED_ALREADY... no
checking for curlopt_unix_socket_path... no
checking for curl_easy_escape... no
checking for rb_thread_blocking_region()... yes
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
creating curb_config.h
creating Makefile

make "DESTDIR="
compiling curb.c
In file included from curb.c:8:
In file included from ./curb.h:12:
In file included from /opt/local/include/curl/curl.h:35:
/opt/local/include/curl/curlrules.h:143:6: error: '**curl_rule_01**' declared as an array with a negative size
    [CurlchkszEQ(long, CURL_SIZEOF_LONG)];
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/curl/curlrules.h:132:27: note: expanded from macro 'CurlchkszEQ'
#define CurlchkszEQ(t, s) sizeof(t) == s ? 1 : -1
                          ^~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/curl/curlrules.h:153:6: error: '**curl_rule_02**' declared as an array with a negative size
    [CurlchkszEQ(curl_off_t, CURL_SIZEOF_CURL_OFF_T)];
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/curl/curlrules.h:132:27: note: expanded from macro 'CurlchkszEQ'
#define CurlchkszEQ(t, s) sizeof(t) == s ? 1 : -1
                          ^~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make: **\* [curb.o] Error 1

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/curb-0.9.3 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/curb-0.9.3/ext/gem_make.out

**Comment by kirbs-** [comment]
Check out [curb's FAQs](https://github.com/taf2/curb/wiki/FAQ). Maybe this will work:

> Snow Leopard (OSX 10.6) - build errors
> 
> ```
> sudo rake install
> (in /Users/xxxx/work/github/curb)
> gcc -I. -I. -I/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin10.0 -I. -DRUBY_EXTCONF_H=\"curb_config.h\"  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE   -fno-common -arch i386 -arch x86_64 -g -Os -pipe -fno-common -DENABLE_DTRACE  -fno-common  -pipe -fno-common  -I/opt/local/include -Wall  -c curb.c
> In file included from /opt/local/include/curl/curl.h:36,
>              from curb.h:12,
>              from curb.c:8:
> /opt/local/include/curl/curlrules.h:144: error: size of array ‘__curl_rule_01__’ is negative
> /opt/local/include/curl/curlrules.h:154: error: size of array ‘__curl_rule_02__’ is negative
> lipo: can't open input file: /var/tmp//ccmASHN7.out (No such file or directory)
> make: *** [curb.o] Error 1
> rake aborted!
> Make failed (status 2)
> /Users/xxxx/work/github/curb/Rakefile:60
> (See full trace by running task with --trace)
> ```
> 
> Solution
> 
> `sudo port install curl +universal`
> 
> If the above doesn't output something like: (notice the x86_64) (if you see ppc) something is wrong!
> 
> ```
> sudo port install curl +universal
>  --->  Computing dependencies for curl
>  --->  Fetching curl
>  --->  Verifying checksum(s) for curl
>  --->  Extracting curl
>  --->  Configuring curl
>  --->  Configuring curl for architecture x86_64
>  --->  Configuring curl for architecture i386
>  --->  Building curl
>  --->  Building curl for architecture x86_64
>  --->  Building curl for architecture i386
>  --->  Staging curl into destroot
>  --->  Staging curl into destroot for architecture x86_64
>  --->  Staging curl into destroot for architecture i386
>  --->  Installing curl @7.19.6_0+universal
>  --->  Deactivating curl @7.19.6_0
>  --->  Activating curl @7.19.6_0+universal
>  --->  Cleaning curl
> ```
> 
> Alt solution
> 
>  `sudo env ARCHFLAGS="-arch x86_64" gem install curb`

**Comment by nguinasso** [comment]
I did
sudo env ARCHFLAGS="-arch x86_64" gem install curb 
and
sudo env ARCHFLAGS="-arch x86_64" gem install curb

and it installed correctly.

I was able to attach to my thermostat and execute some methods using irb. 

There does not appear to be a method for Current Runtime that is on my phone app under Settings/Thermostat Info. This, I think, gives the length of time the current on cycle has been running.

Thanks for your efforts in helping someone who has zero experience with either ruby or gem.

**Comment by kirbs-** [comment]
Glad to help. You'll see a bunch of option and meta data buried in the initial response. I haven't seen the current run time anywhere in the phone app. This value is only populated if the system is active. It resets to 00:00 as soon as heating/cooling turns off.
