### ISSUE TITLE
change thermostats

### ISSUE THREAD

**Issue by TheRevJohn** [kirbs-/sensi#3]
Is there a way to change the thermostat that is controlled?  I have 3 thermostats and I can only control the first one I installed.  Program works well.

**Comment by kirbs-** [comment]
I think so, but the thermostat's device ids are probably buried in mythermostat's JSON response. You can access the parsed response by calling `thermostat.thermostat_connection.thermostat_info`. This should be a JSON array of thermostats. The device id you need is called `ICD` by the mythermostat. I'm pretty sure the ids don't change.

Once you have all the device ids, you'll have to manually connect to each thermostat. **Do not call `thermostat.connect` directly.** This will always connect you to the first thermostat on the account.

```ruby
thermostat = Sensi::Thermostat.new(username, password)
thermostat.account.login
thermostat.get_account_info
thermostat.thermostat_connection.thermostat_info # this should list all thermostats on the account.

# store the individual device ids
device1 = 'xx-xx-xx-xx-xx-xx-xx-xx'
device2 = 'xx-xx-xx-xx-xx-xx-xx-xx'
device3 = 'xx-xx-xx-xx-xx-xx-xx-xx'

# save the new device id into the icd variable
thermostat.icd = device1
thermostat.connect_to_device

# do stuff
...

# switch to another thermostat
thermostat.thermostat_connection.stop_polling
thermostat.icd = device2
thermostat.connect_to_device

# do some more stuff
# etc

thermostat.disconnect
```

**Comment by TheRevJohn** [comment]
Thank you, this is very helpful.
